package com.pearson.pix.dto.common;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 *  ###  Generated by Oracle TopLink Workbench 10.1.3.0.0 - Tue Sep 18 13:54:54 GMT+05:30 2007.  ###
 */

public class TitlePrinting implements Serializable {

	private String activeFlag;
	private Date creationDateTime;
	private String isbn10;
	private String isbn13;
	private Date modDateTime;
	private String printNo;
	private BigDecimal titleId;
	private String titleType;
	private String paperGrade;
	private Integer basisWeight;
	private Integer rollSize;

public Integer getBasisWeight() {
		return basisWeight;
	}

	public void setBasisWeight(Integer basisWeight) {
		this.basisWeight = basisWeight;
	}

	public String getPaperGrade() {
		return paperGrade;
	}

	public void setPaperGrade(String paperGrade) {
		this.paperGrade = paperGrade;
	}

	public Integer getRollSize() {
		return rollSize;
	}

	public void setRollSize(Integer rollSize) {
		this.rollSize = rollSize;
	}

public TitlePrinting() {
	super();
}

public String getActiveFlag() {
	return this.activeFlag;
}

public Date getCreationDateTime() {
	return this.creationDateTime;
}

public String getIsbn10() {
	return this.isbn10;
}

public String getIsbn13() {
	return this.isbn13;
}

public Date getModDateTime() {
	return this.modDateTime;
}

public String getPrintNo() {
	return this.printNo;
}

public BigDecimal getTitleId() {
	return this.titleId;
}

public String getTitleType() {
	return this.titleType;
}

public void setActiveFlag(String activeFlag) {
	this.activeFlag = activeFlag;
}

public void setCreationDateTime(Date creationDateTime) {
	this.creationDateTime = creationDateTime;
}

public void setIsbn10(String isbn10) {
	this.isbn10 = isbn10;
}

public void setIsbn13(String isbn13) {
	this.isbn13 = isbn13;
}

public void setModDateTime(Date modDateTime) {
	this.modDateTime = modDateTime;
}

public void setPrintNo(String printNo) {
	this.printNo = printNo;
}

public void setTitleId(BigDecimal titleId) {
	this.titleId = titleId;
}

public void setTitleType(String titleType) {
	this.titleType = titleType;
}

}
