package com.pearson.pix.dto.purchaseorder;

import java.io.Serializable;
import java.math.BigDecimal;

/**
 *  ###  Generated by Oracle TopLink Workbench 10.1.3.0.0 - Wed Jul 25 17:48:29 GMT+05:30 2007.  ###
 */

public class POLinePartyContact implements Serializable {

	private String contactFirstName;
	private String contactLastName;
	private BigDecimal contactNo;
	private String contactType;
	private String email;
	private String fax;
	private String mobile;
	private String phone;
	private BigDecimal poId;
	private BigDecimal poLineNo;
	private BigDecimal poVersion;
	private String san;

public POLinePartyContact() {
	super();
}

public String getContactFirstName() {
	return this.contactFirstName;
}

public String getContactLastName() {
	return this.contactLastName;
}

public BigDecimal getContactNo() {
	return this.contactNo;
}

public String getContactType() {
	return this.contactType;
}

public String getEmail() {
	return this.email;
}

public String getFax() {
	return this.fax;
}

public String getMobile() {
	return this.mobile;
}

public String getPhone() {
	return this.phone;
}

public BigDecimal getPoId() {
	return this.poId;
}

public BigDecimal getPoLineNo() {
	return this.poLineNo;
}

public BigDecimal getPoVersion() {
	return this.poVersion;
}

public String getSan() {
	return this.san;
}

public void setContactFirstName(String contactFirstName) {
	this.contactFirstName = contactFirstName;
}

public void setContactLastName(String contactLastName) {
	this.contactLastName = contactLastName;
}

public void setContactNo(BigDecimal contactNo) {
	this.contactNo = contactNo;
}

public void setContactType(String contactType) {
	this.contactType = contactType;
}

public void setEmail(String email) {
	this.email = email;
}

public void setFax(String fax) {
	this.fax = fax;
}

public void setMobile(String mobile) {
	this.mobile = mobile;
}

public void setPhone(String phone) {
	this.phone = phone;
}

public void setPoId(BigDecimal poId) {
	this.poId = poId;
}

public void setPoLineNo(BigDecimal poLineNo) {
	this.poLineNo = poLineNo;
}

public void setPoVersion(BigDecimal poVersion) {
	this.poVersion = poVersion;
}

public void setSan(String san) {
	this.san = san;
}

}
