package com.pearson.pix.dto.purchaseorder;

import java.math.BigDecimal;
import java.util.Collection;
import java.util.Date;
import java.util.Vector;

import com.pearson.pix.dto.common.Country;

/**
 *  ###  Generated by Oracle TopLink Workbench 10.1.3.0.0 - Wed Jul 26 19:52:09 IST 2006.  ###
 */

public class POSuppliedCompParty {

	private Date modDateTime;
	private Date creationDateTime;
	private String modifiedBy;
	private String createdBy;
	private Country countryDetail;
	private String url;
	private String acknowledgeFlag;
	private String comments;
	private String finishedVendorFlag;
	private String partyType;
	private String postalCode;
	private String state;
	private String city;
	private String address4;
	private String address3;
	private String address2;
	private String address1;
	private String orgUnitName;
	private String orgUnitCode;
	private String name3;
	private String name2;
	private String name1;
	private String san;
	private BigDecimal suppCompLineNo;
	private BigDecimal poLineNo;
	private BigDecimal poVersion;
	private BigDecimal poId;
	private Collection contactCollection;

public POSuppliedCompParty() {
	super();
	this.contactCollection = new Vector();
}

public String getAcknowledgeFlag() {
	return this.acknowledgeFlag;
}

public String getAddress1() {
	return this.address1;
}

public String getAddress2() {
	return this.address2;
}

public String getAddress3() {
	return this.address3;
}

public String getAddress4() {
	return this.address4;
}

public String getCity() {
	return this.city;
}

public String getComments() {
	return this.comments;
}

public Collection getContactCollection() {
	return this.contactCollection;
}

public Country getCountryDetail() {
	return this.countryDetail;
}

public String getCreatedBy() {
	return this.createdBy;
}

public Date getCreationDateTime() {
	return this.creationDateTime;
}

public String getFinishedVendorFlag() {
	return this.finishedVendorFlag;
}

public Date getModDateTime() {
	return this.modDateTime;
}

public String getModifiedBy() {
	return this.modifiedBy;
}

public String getName1() {
	return this.name1;
}

public String getName2() {
	return this.name2;
}

public String getName3() {
	return this.name3;
}

public String getOrgUnitCode() {
	return this.orgUnitCode;
}

public String getOrgUnitName() {
	return this.orgUnitName;
}

public String getPartyType() {
	return this.partyType;
}

public BigDecimal getPoId() {
	return this.poId;
}

public BigDecimal getPoLineNo() {
	return this.poLineNo;
}

public BigDecimal getPoVersion() {
	return this.poVersion;
}

public String getPostalCode() {
	return this.postalCode;
}

public String getSan() {
	return this.san;
}

public String getState() {
	return this.state;
}

public BigDecimal getSuppCompLineNo() {
	return this.suppCompLineNo;
}

public String getUrl() {
	return this.url;
}

public void setAcknowledgeFlag(String acknowledgeFlag) {
	this.acknowledgeFlag = acknowledgeFlag;
}

public void setAddress1(String address1) {
	this.address1 = address1;
}

public void setAddress2(String address2) {
	this.address2 = address2;
}

public void setAddress3(String address3) {
	this.address3 = address3;
}

public void setAddress4(String address4) {
	this.address4 = address4;
}

public void setCity(String city) {
	this.city = city;
}

public void setComments(String comments) {
	this.comments = comments;
}

public void setContactCollection(Collection contactCollection) {
	this.contactCollection = contactCollection;
}

public void setCountryDetail(Country countryDetail) {
	this.countryDetail = countryDetail;
}

public void setCreatedBy(String createdBy) {
	this.createdBy = createdBy;
}

public void setCreationDateTime(Date creationDateTime) {
	this.creationDateTime = creationDateTime;
}

public void setFinishedVendorFlag(String finishedVendorFlag) {
	this.finishedVendorFlag = finishedVendorFlag;
}

public void setModDateTime(Date modDateTime) {
	this.modDateTime = modDateTime;
}

public void setModifiedBy(String modifiedBy) {
	this.modifiedBy = modifiedBy;
}

public void setName1(String name1) {
	this.name1 = name1;
}

public void setName2(String name2) {
	this.name2 = name2;
}

public void setName3(String name3) {
	this.name3 = name3;
}

public void setOrgUnitCode(String orgUnitCode) {
	this.orgUnitCode = orgUnitCode;
}

public void setOrgUnitName(String orgUnitName) {
	this.orgUnitName = orgUnitName;
}

public void setPartyType(String partyType) {
	this.partyType = partyType;
}

public void setPoId(BigDecimal poId) {
	this.poId = poId;
}

public void setPoLineNo(BigDecimal poLineNo) {
	this.poLineNo = poLineNo;
}

public void setPoVersion(BigDecimal poVersion) {
	this.poVersion = poVersion;
}

public void setPostalCode(String postalCode) {
	this.postalCode = postalCode;
}

public void setSan(String san) {
	this.san = san;
}

public void setState(String state) {
	this.state = state;
}

public void setSuppCompLineNo(BigDecimal suppCompLineNo) {
	this.suppCompLineNo = suppCompLineNo;
}

public void setUrl(String url) {
	this.url = url;
}

}
