/*
 * Generated by XDoclet - Do not edit!
 */
package com.pearson.pix.business.purchaseorder.interfaces;

import java.math.BigDecimal;
import java.util.Collection;
import java.util.HashMap;

import com.pearson.pix.dto.purchaseorder.POHeader;
import com.pearson.pix.dto.purchaseorder.POSuppliedComp;
import com.pearson.pix.exception.AppException;

/**
 * Local interface for PurchaseOrder.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface PurchaseOrderLocal
   extends javax.ejb.EJBLocalObject
{
    /**
     * Business method for displaying the Purchase Order List
     * @return java.util.Collection
     * @J2EE_METHOD  --  displayOrderList
     */
    public Collection displayOrderList(POHeader objpoheader,String startDate,String endDate,String partyType,int userId,String page,int pagination,String orderby,String sort,String sbBDate,String ebBDate) throws AppException;
    
    /**
     * Business method for displaying the Purchase Order Detail
     * 
     * @param poId
     * @param poVersion
     * @param party
     * @param userId
     * @param paperFO
     * @return java.util.HashMap
     * @J2EE_METHOD  --  displayOrderDetail
     */
    public HashMap displayOrderDetail(BigDecimal poId, BigDecimal poVersion,String party,Integer userId,String paperFo) throws AppException;
    
    /**
     * Business method for saving the Order Confirmation
     * 
     * @return java.lang.String
     * @J2EE_METHOD  --  saveOrderConfirmation
     */
    public String saveOrderConfirmation(POHeader poHeader,String orderType) throws AppException;
    
    /**
     * Business method for displaying the Purchase Order Status
     * @return java.util.Collection
     * @J2EE_METHOD  --  displayPurchaseOrderStatus
     */
    public Collection displayPurchaseOrderStatus()throws AppException;
    
    /**
     * Business method for displaying the Purchase Order Line Items for Supplied Components
     * @param poId
     * @param poVersion
     * @return java.util.Collection
     * @J2EE_METHOD  --  displayOrderLineItems
     */
    public Collection displayOrderLineItems(BigDecimal poId, BigDecimal poVersion)throws AppException; 
    
    /**
     * Business method for Accepting multiple Purchase Orders
     * 
     * @param idVersionString
     * @param login
     * @return String 
     */
    public String insertMultiplePOAccept(String idVersionString,String login) throws AppException;
}
