/*
 * Generated by XDoclet - Do not edit!
 */
package com.pearson.pix.business.exporttoexcel.interfaces;

import com.pearson.pix.exception.AppException;


/**
 * Local interface for ExportToExcel.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface ExportToExcelLocal
   extends javax.ejb.EJBLocalObject
{
	/**
	    * <!-- begin-xdoclet-definition -->
	    * @generated //TODO: Must provide implementation for bean method stub This method return ExportToExcelDTO which will get the report details from the database. 
	    * @param objDTO object of ExportToExcelDTO
	    * @return objDTO object of ExportToExcelDTO
	    * @throws RemoteException in case of Remote Exception.
	    * @throws Exception in case of error.    */
	   public com.pearson.pix.dto.exporttoexcel.ExportToExcelDTO getReportDetail(com.pearson.pix.dto.exporttoexcel.ExportToExcelDTO objDTO )
	      throws AppException;
	   /**
	    * <!-- begin-xdoclet-definition -->
	    * @generated //TODO: Must provide implementation for bean method stub This method return ExportToExcelDTO which will get the report details from the database. 
	    * @param objDTO object of ExportToExcelDTO
	    * @return objDTO object of ExportToExcelDTO
	    * @throws RemoteException in case of Remote Exception.
	    * @throws Exception in case of error.    */
	   public com.pearson.pix.dto.exporttoexcel.ExportToExcelDTO getDetail(com.pearson.pix.dto.exporttoexcel.ExportToExcelDTO objDTO )
	      throws AppException;
	   /**
	    * <!-- begin-xdoclet-definition -->
	    * @generated //TODO: Must provide implementation for bean method stub This method return ExportToExcelDTO which will get the report details from the database. 
	    * @param objDTO object of ExportToExcelDTO
	    * @return objDTO object of ExportToExcelDTO
	    * @throws RemoteException in case of Remote Exception.
	    * @throws Exception in case of error.    */
	   public com.pearson.pix.dto.exporttoexcel.ExportToExcelDTO getMillDetail(com.pearson.pix.dto.exporttoexcel.ExportToExcelDTO objDTO )
	      throws AppException;
	   /**
	    * <!-- begin-xdoclet-definition -->
	    * @generated //TODO: Must provide implementation for bean method stub This method return ExportToExcelDTO which will get the report details from the database. 
	    * @param objDTO object of ExportToExcelDTO
	    * @return objDTO object of ExportToExcelDTO
	    * @throws RemoteException in case of Remote Exception.
	    * @throws Exception in case of error.    */
	   public com.pearson.pix.dto.exporttoexcel.ExportToExcelDTO getPurchaseMillDetail(com.pearson.pix.dto.exporttoexcel.ExportToExcelDTO objDTO )
	      throws AppException;
	   /**
	    * <!-- begin-xdoclet-definition -->
	    * @generated //TODO: Must provide implementation for bean method stub This method return ExportToExcelDTO which will get the report details from the database. 
	    * @param objDTO object of ExportToExcelDTO
	    * @return objDTO object of ExportToExcelDTO
	    * @throws RemoteException in case of Remote Exception.
	    * @throws Exception in case of error.    */
	   public com.pearson.pix.dto.exporttoexcel.ExportToExcelDTO getPurchaseDetail(com.pearson.pix.dto.exporttoexcel.ExportToExcelDTO objDTO )
	      throws AppException;
	   /**
	    * <!-- begin-xdoclet-definition -->
	    * @generated //TODO: Must provide implementation for bean method stub This method return ExportToExcelDTO which will get the report details from the database. 
	    * @param objDTO object of ExportToExcelDTO
	    * @return objDTO object of ExportToExcelDTO
	    * @throws RemoteException in case of Remote Exception.
	    * @throws Exception in case of error.    */
	   public com.pearson.pix.dto.exporttoexcel.ExportToExcelDTO getGoodReceiptDetail(com.pearson.pix.dto.exporttoexcel.ExportToExcelDTO objDTO )
	      throws AppException;
	   /**
	    * <!-- begin-xdoclet-definition -->
	    * @generated //TODO: Must provide implementation for bean method stub This method return ExportToExcelDTO which will get the GR hiostory details from the database. 
	    * @param objDTO object of ExportToExcelDTO
	    * @return objDTO object of ExportToExcelDTO
	    * @throws RemoteException in case of Remote Exception.
	    * @throws Exception in case of error. 
	    * @author anshu.bhardwaj   */
	   public com.pearson.pix.dto.exporttoexcel.ExportToExcelDTO getGoodReceiptPaperHistory(com.pearson.pix.dto.exporttoexcel.ExportToExcelDTO objDTO )
	      throws AppException;
	   /**
	    * <!-- begin-xdoclet-definition -->
	    * @generated //TODO: Must provide implementation for bean method stub This method return ExportToExcelDTO which will get the GR hiostory details from the database. 
	    * @param objDTO object of ExportToExcelDTO
	    * @return objDTO object of ExportToExcelDTO
	    * @throws RemoteException in case of Remote Exception.
	    * @throws Exception in case of error. 
	    * @author anshu.bhardwaj   */
	   public com.pearson.pix.dto.exporttoexcel.ExportToExcelDTO getGoodReceiptPaperNew(com.pearson.pix.dto.exporttoexcel.ExportToExcelDTO objDTO )
	      throws AppException;

	   
	   // GR popup
	   public com.pearson.pix.dto.exporttoexcel.ExportToExcelDTO getGoodReceiptPaperPop(com.pearson.pix.dto.exporttoexcel.ExportToExcelDTO objDTO )
	      throws AppException;

	   // CU GR popup
	   public com.pearson.pix.dto.exporttoexcel.ExportToExcelDTO cuOwnedQtyPopup(com.pearson.pix.dto.exporttoexcel.ExportToExcelDTO objDTO )
	      throws AppException;

	   
		// DM popup
	   public com.pearson.pix.dto.exporttoexcel.ExportToExcelDTO getDMPaperPop(com.pearson.pix.dto.exporttoexcel.ExportToExcelDTO objDTO )
	      throws AppException;


		// DM popup
	   public com.pearson.pix.dto.exporttoexcel.ExportToExcelDTO getDMHistoryPaperPop(com.pearson.pix.dto.exporttoexcel.ExportToExcelDTO objDTO )
	      throws AppException;
   
	   
	   
	   
	   /**
	    * <!-- begin-xdoclet-definition -->
	    * @generated //TODO: Must provide implementation for bean method stub This method return ExportToExcelDTO which will get the report details from the database. 
	    * @param objDTO object of ExportToExcelDTO
	    * @return objDTO object of ExportToExcelDTO
	    * @throws RemoteException in case of Remote Exception.
	    * @throws Exception in case of error.    */
	   public com.pearson.pix.dto.exporttoexcel.ExportToExcelDTO getDeliveryDetail(com.pearson.pix.dto.exporttoexcel.ExportToExcelDTO objDTO )
	      throws AppException;
	   /**
	    * <!-- begin-xdoclet-definition -->
	    * @generated //TODO: Must provide implementation for bean method stub This method return ExportToExcelDTO which will get the report details from the database. 
	    * @param objDTO object of ExportToExcelDTO
	    * @return objDTO object of ExportToExcelDTO
	    * @throws RemoteException in case of Remote Exception.
	    * @throws Exception in case of error.    */
	   public com.pearson.pix.dto.exporttoexcel.ExportToExcelDTO getDeliveryMessageNewMill(com.pearson.pix.dto.exporttoexcel.ExportToExcelDTO objDTO )
	      throws AppException;
	   /**
	    * <!-- begin-xdoclet-definition -->
	    * @generated //TODO: Must provide implementation for bean method stub This method return ExportToExcelDTO which will get the report details from the database. 
	    * @param objDTO object of ExportToExcelDTO
	    * @return objDTO object of ExportToExcelDTO
	    * @throws RemoteException in case of Remote Exception.
	    * @throws Exception in case of error.    */
	   public com.pearson.pix.dto.exporttoexcel.ExportToExcelDTO getDeliveryMessageHistory(com.pearson.pix.dto.exporttoexcel.ExportToExcelDTO objDTO )
	      throws AppException;
	   /**
	    * <!-- begin-xdoclet-definition -->
	    * @generated //TODO: Must provide implementation for bean method stub This method return ExportToExcelDTO which will get the report details from the database. 
	    * @param objDTO object of ExportToExcelDTO
	    * @return objDTO object of ExportToExcelDTO
	    * @throws RemoteException in case of Remote Exception.
	    * @throws Exception in case of error.    */
	   public com.pearson.pix.dto.exporttoexcel.ExportToExcelDTO getInboxDeliveryMessageHistory(com.pearson.pix.dto.exporttoexcel.ExportToExcelDTO objDTO )
	      throws AppException;
	   /**
	    * <!-- begin-xdoclet-definition -->
	    * @generated //TODO: Must provide implementation for bean method stub This method return ExportToExcelDTO which will get the report details from the database. 
	    * @param objDTO object of ExportToExcelDTO
	    * @return objDTO object of ExportToExcelDTO
	    * @throws RemoteException in case of Remote Exception.
	    * @throws Exception in case of error.    */
	   public com.pearson.pix.dto.exporttoexcel.ExportToExcelDTO getBookSpecDetail(com.pearson.pix.dto.exporttoexcel.ExportToExcelDTO objDTO )
	      throws AppException;
	   /**
	    * <!-- begin-xdoclet-definition -->
	    * @generated //TODO: Must provide implementation for bean method stub This method return ExportToExcelDTO which will get the report details from the database. 
	    * @param objDTO object of ExportToExcelDTO
	    * @return objDTO object of ExportToExcelDTO
	    * @throws RemoteException in case of Remote Exception.
	    * @throws Exception in case of error.    */
	   public com.pearson.pix.dto.exporttoexcel.ExportToExcelDTO getOrderStatusDetail(com.pearson.pix.dto.exporttoexcel.ExportToExcelDTO objDTO )
	      throws AppException;
	   
	   /**
	    * <!-- begin-xdoclet-definition -->
	    * @generated //TODO: Must provide implementation for bean method stub This method return ExportToExcelDTO which will get the delivery message approval details from the database. 
	    * @param objDTO object of ExportToExcelDTO
	    * @return objDTO object of ExportToExcelDTO
	    * @throws RemoteException in case of Remote Exception.
	    * @throws Exception in case of error.    */
	   public com.pearson.pix.dto.exporttoexcel.ExportToExcelDTO getDeliveryMessageApprovalDetail(com.pearson.pix.dto.exporttoexcel.ExportToExcelDTO objDTO )
	      throws AppException;
	   //changes for Displaying Outstanding Delivery Report
	   /**
	    * <!-- begin-xdoclet-definition -->
	    * @generated //TODO: Must provide implementation for bean method stub This method return ExportToExcelDTO which will get the outstanding delivery report details from the database. 
	    * @param objDTO object of ExportToExcelDTO
	    * @return objDTO object of ExportToExcelDTO
	    * @throws RemoteException in case of Remote Exception.
	    * @throws Exception in case of error.    */
	   public com.pearson.pix.dto.exporttoexcel.ExportToExcelDTO getOutstandingDetail(com.pearson.pix.dto.exporttoexcel.ExportToExcelDTO objDTO )
	      throws AppException;
	   // end of changes for Displaying Outstanding Delivery Report
	   /**
	    * <!-- begin-xdoclet-definition -->
	    * @generated //TODO: Must provide implementation for bean method stub This method return ExportToExcelDTO which will get the outstanding delivery report details from the database. 
	    * @param objDTO object of ExportToExcelDTO
	    * @return objDTO object of ExportToExcelDTO
	    * @throws RemoteException in case of Remote Exception.
	    * @throws Exception in case of error.
	    */
	   public com.pearson.pix.dto.exporttoexcel.ExportToExcelDTO getPotentialARPDetail(com.pearson.pix.dto.exporttoexcel.ExportToExcelDTO objDTO )
	      throws AppException;
	   
   
}
