/*
 * Generated by XDoclet - Do not edit!
 */
package com.pearson.pix.business.exporttoexcel.interfaces;

/**
 * Local home interface for ExportToExcel.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface ExportToExcelLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/ExportToExcelLocal";
   public static final String JNDI_NAME="java:global/PIXApplication/PIXApplicationEJB/ExportToExcel!com.pearson.pix.business.exporttoexcel.interfaces.ExportToExcelLocalHome";//"ExportToExcelLocal";

   public com.pearson.pix.business.exporttoexcel.interfaces.ExportToExcelLocal create()
      throws javax.ejb.CreateException;

}
