/*
 * Generated by XDoclet - Do not edit!
 */
package com.pearson.pix.business.costaccounting.interfaces;

import java.math.BigDecimal;
import java.util.Collection;
import java.util.LinkedHashMap;

import com.pearson.pix.dto.deliverymessage.DeliveryMessage;
import com.pearson.pix.dto.purchaseorder.POHeader;
import com.pearson.pix.exception.AppException;

/**
 * Local interface for CostAccounting.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface CostAccountingLocal
   extends javax.ejb.EJBLocalObject
{
   /**
    * An example business method
    * @throws EJBException Thrown if method fails due to system-level error.    */
   public void replaceWithRealBusinessMethod(  ) throws javax.ejb.EJBException;
   
   /**
    * Business method for displaying the Delivery Messages Approval List
    * 
    * @return java.util.Collection
    * @J2EE_METHOD  --  getDmApprovalList
    */
   public Collection getDmApprovalList(POHeader poHeaderTemp,int pagination,String objorderby,String objsort,Integer userId,String materialNoFilter,String delMsgNoFilter,String millMerchantFilter,String printerFilter,String startDate,String endDate) throws AppException;
   
   /**
    * Business method for Approving multiple Delivery Message
    * 
    * @param idVersionString
    * @param userId
    * @return String 
    */
   public String insertMultipleDMApprove(String idVersionString,Integer userId,String ownrshpMode) throws AppException;
   
   /**
    * Calls corresponding Business method of costAccounting EJB for the purpose of 
    * getting dropdown values for filter
    * 
    * @return java.util.LinkedHashMap
    */
   
   public LinkedHashMap getFilterDropDowns(Integer userId) throws AppException;
   
   /**
    * Calls corresponding Business method of costAccounting EJB for the purpose of 
    * updating the quantity of delivery message detail.
    * 
    
    */
   
   public String updateDeliveryMessageLine(DeliveryMessage objDeliveryMessage,Integer messageId , BigDecimal poId , BigDecimal poVersion,Integer userId) throws AppException;
   
   
   
   
}
