/*
 * Generated by XDoclet - Do not edit!
 */
package com.pearson.pix.business.costaccounting.interfaces;

/**
 * Local home interface for CostAccounting.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface CostAccountingLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/CostAccountingLocal";
   public static final String JNDI_NAME="java:global/PIXApplication/PIXApplicationEJB/CostAccounting!com.pearson.pix.business.costaccounting.interfaces.CostAccountingLocalHome";//"CostAccountingLocal";

   public com.pearson.pix.business.costaccounting.interfaces.CostAccountingLocal create()
      throws javax.ejb.CreateException;

}
