/*
 * Generated by XDoclet - Do not edit!
 */
package com.pearson.pix.business.deliverymessage.interfaces;

/**
 * Local home interface for DeliveryMessage.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface DeliveryMessageLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/DeliveryMessageLocal";
   public static final String JNDI_NAME="java:global/PIXApplication/PIXApplicationEJB/DeliveryMessage!com.pearson.pix.business.deliverymessage.interfaces.DeliveryMessageLocalHome";//"DeliveryMessageLocal";

   public com.pearson.pix.business.deliverymessage.interfaces.DeliveryMessageLocal create()
      throws javax.ejb.CreateException;

}
