package com.pearson.pix.dto.arptitlesetup;

import java.io.Serializable;
import java.math.BigDecimal;

/**
 *  ###  Generated by Oracle TopLink Workbench 10.1.3.0.0 - Tue Mar 23 12:14:48 IST 2010.  ###
 */

public class ArpSetUpResult implements Serializable{  

	private static final long serialVersionUID = -5145007399961271318L;
	
	private Integer outCode;

	private String outMessage;

	private Integer titleId;

	private String isbn;
	
	private BigDecimal eventId;

	public ArpSetUpResult() {
		super();
	}
	
	/**
	 * @return the outCode
	 */
	public Integer getOutCode() {
		return outCode;
	}
	
	/**
	 * @param outCode the outCode to set
	 */
	public void setOutCode(Integer outCode) {
		this.outCode = outCode;
	}
	
	/**
	 * @return the outMessage
	 */
	public String getOutMessage() {
		return outMessage;
	}
	
	/**
	 * @param outMessage the outMessage to set
	 */
	public void setOutMessage(String outMessage) {
		this.outMessage = outMessage;
	}
	
	/**
	 * @return the titleId
	 */
	public Integer getTitleId() {
		return titleId;
	}
	
	/**
	 * @param titleId the titleId to set
	 */
	public void setTitleId(Integer titleId) {
		this.titleId = titleId;
	}
	
	/**
	 * @return the isbn
	 */
	public String getIsbn() {
		return isbn;
	}
	
	/**
	 * @param isbn the isbn to set
	 */
	public void setIsbn(String isbn) {
		this.isbn = isbn;
	}
	
	/**
	 * @return the eventId
	 */
	public BigDecimal getEventId() {
		return eventId;
	}
	
	/**
	 * @param eventId the eventId to set
	 */
	public void setEventId(BigDecimal eventId) {
		this.eventId = eventId;
	}

}
