package com.pearson.pix.dto.arptitlesetup;

import java.math.BigDecimal;
import java.util.Date;

/**
 *  ###  Generated by Oracle TopLink Workbench 10.1.3.0.0 - Tue Mar 23 14:31:45 IST 2010.  ###
 */

public class FlipreportmasterArp {

	private BigDecimal actionFlag;
	private BigDecimal delIndic;
	private BigDecimal eventId;
	private Date eventLogdate;
	private Date logDate;
	private BigDecimal titleId;
	private BigDecimal transactTypeId;
	private BigDecimal vendorplantId;

public FlipreportmasterArp() {
	super();
}

public BigDecimal getActionFlag() {
	return this.actionFlag;
}

public BigDecimal getDelIndic() {
	return this.delIndic;
}

public BigDecimal getEventId() {
	return this.eventId;
}

public Date getEventLogdate() {
	return this.eventLogdate;
}

public Date getLogDate() {
	return this.logDate;
}

public BigDecimal getTitleId() {
	return this.titleId;
}

public BigDecimal getTransactTypeId() {
	return this.transactTypeId;
}

public BigDecimal getVendorplantId() {
	return this.vendorplantId;
}

public void setActionFlag(BigDecimal actionFlag) {
	this.actionFlag = actionFlag;
}

public void setDelIndic(BigDecimal delIndic) {
	this.delIndic = delIndic;
}

public void setEventId(BigDecimal eventId) {
	this.eventId = eventId;
}

public void setEventLogdate(Date eventLogdate) {
	this.eventLogdate = eventLogdate;
}

public void setLogDate(Date logDate) {
	this.logDate = logDate;
}

public void setTitleId(BigDecimal titleId) {
	this.titleId = titleId;
}

public void setTransactTypeId(BigDecimal transactTypeId) {
	this.transactTypeId = transactTypeId;
}

public void setVendorplantId(BigDecimal vendorplantId) {
	this.vendorplantId = vendorplantId;
}

}
