package com.pearson.pix.dto.arptitlesetup;

import java.math.BigDecimal;

/**
 *  ###  Generated by Oracle TopLink Workbench 10.1.3.0.0 - Tue Mar 23 12:14:48 IST 2010.  ###
 */

public class WqstatesArp {

	private String description;
	private String mnemonic;
	private BigDecimal id;

public WqstatesArp() {
	super();
}

public String getDescription() {
	return this.description;
}

public BigDecimal getId() {
	return this.id;
}

public String getMnemonic() {
	return this.mnemonic;
}

public void setDescription(String description) {
	this.description = description;
}

public void setId(BigDecimal id) {
	this.id = id;
}

public void setMnemonic(String mnemonic) {
	this.mnemonic = mnemonic;
}

}
