/*
 * Generated by XDoclet - Do not edit!
 */
package com.pearson.pix.business.orderstatus.interfaces;

import java.util.Vector;

import com.pearson.pix.dto.orderstatus.OrderStatus;
import com.pearson.pix.exception.AppException;

/**
 * Local interface for OrderStatus.
  * @author Dabndu Thirupathi
 * @version 1.0
 */
public interface OrderStatusLocal
   extends javax.ejb.EJBLocalObject
{
	 /**
     * Business method for displaying the Order Status List
     * @param poId
     * @param poVersion
     * @param Pagination
     * @param OrderBy
     * @param Sort
     * @return java.util.Vector
     * @J2EE_METHOD  --  displayOrderStatusList
     */
	public Vector displayOrderStatusList(Integer objPoId,Integer objPoVersion,Integer objPagination,String objOrderBy,String objSort)throws AppException;
    
    /**
     * Business method for displaying the Order Status Detail
     * 
     * @param poId
     * @param poVersion
     * @param statusId
     * @return java.util.Vector
     * @J2EE_METHOD  --  displayOrderStatusDetail
     */
	public Vector displayOrderStatusDetail(Integer poId,Integer poVersion ,String statusId) throws AppException;
    
	/**
     * Business method for displaying the Basic Information for Order Status submit.
     * 
     * @param poId
     * @param poVersion
     * @return java.util.HashMap
     * @J2EE_METHOD  --  displayBasicOrderStatusInfo
     */
    public java.util.HashMap displayBasicOrderStatusInfo(Integer poId,Integer poVersion) throws AppException;
    
    /**
     * Business method for saving the information for Order Status.
     * @param OrderStatus
     * @param objPoId
     * @param PoVersion
     * @param PoNo
     * @param Rno
     * @param User
     * @return java.lang.String
     * @J2EE_METHOD  --  saveOrderStatus
     */
    public String saveOrderStatus(OrderStatus objOrderStatus,Integer objPoId,Integer objPoVersion,String objPoNo,Integer objRno,String objUser) throws AppException;

}
