package com.pearson.pix.dto.admin;

import java.io.Serializable;
import java.util.Date;

/**
 *  ###  Generated by Oracle TopLink Workbench 10.1.3.0.0 - Mon Sep 18 13:18:48 IST 2006.  ###
 */

public class UserParty implements Serializable {

	private Integer createdBy;
	private Date creationDateTime;
	private Date modDateTime;
	private Integer modifiedBy;
	private String san;
	private Integer userId;

public UserParty() {
	super();
}

public Integer getCreatedBy() {
	return this.createdBy;
}

public Date getCreationDateTime() {
	return this.creationDateTime;
}

public Date getModDateTime() {
	return this.modDateTime;
}

public Integer getModifiedBy() {
	return this.modifiedBy;
}

public String getSan() {
	return this.san;
}

public Integer getUserId() {
	return this.userId;
}

public void setCreatedBy(Integer createdBy) {
	this.createdBy = createdBy;
}

public void setCreationDateTime(Date creationDateTime) {
	this.creationDateTime = creationDateTime;
}

public void setModDateTime(Date modDateTime) {
	this.modDateTime = modDateTime;
}

public void setModifiedBy(Integer modifiedBy) {
	this.modifiedBy = modifiedBy;
}


public void setSan(String san) {
	this.san = san;
}

public void setUserId(Integer userId) {
	this.userId = userId;
}

}
